spring:
  application:
    name: userservice

  datasource:
    url: jdbc:postgresql://localhost:5432/fitness_user_db
    username: postgres
    password: juju2001

  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
